### ISSUE TITLE
Contribute to Xamarin.Forms

### ISSUE THREAD

**Issue by wcoder** [Intelliabb/XamarinControls#10]
Hi, awesome checkbox!

Maybe you want to contribute to Xamarin.Forms:

https://github.com/xamarin/Xamarin.Forms/issues/1728

**Comment by JADSN** [comment]
You can see https://github.com/enisn/Xamarin.Forms.InputKit for more ideas

**Comment by hnabbasi** [comment]
I would love to submit this as PR. But from the conversations I've had with other developers and read online, it's the iOS that can be an issue. Since they don't have a native control, should we put one out till iOS gets a native control, should we bring it form MacOS, etc... 
Someone mentioned that Xamarin.Forms may want to have such controls under a different namespace maybe to allow folks to have cross-platform controls without native offerings restrictions. meh.

I will submit a PR and see where that goes. Thank you.

**Comment by xleon** [comment]
I was going to use this control until I saw the skia dependency. That library is adding massive weight to the final app. I don´t think any xamarin.forms PR will be merged with skia as a dependency, right?

**Comment by hnabbasi** [comment]
I don't think so. For the PR, I will be drawing using core APIs 🤓
